#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

use CLI\Kernel;
use App\Core\Env;
use CLI\Commands\KeyGenerateCommand;

Env::load(__DIR__ . '/.env');   

$command = $argv[1] ?? null;

$kernel = new Kernel();
$kernel->handle($argv);