<?php

declare(strict_types=1);

namespace App\Core\Components;

use RuntimeException;
use Throwable;

class ComponentRenderer
{
    protected string $cachePath;

    protected ?\App\Core\Pranchi $pranchi = null;

    public function __construct(
        ?string $cachePath = null
    ) {
        $this->cachePath = rtrim(
            $cachePath ?? base_path("bootstrap/cache/components"),
            DIRECTORY_SEPARATOR
        ) . DIRECTORY_SEPARATOR;

        if (!is_dir($this->cachePath)) {
            if (!mkdir(
                $this->cachePath,
                0775,
                true
            )) {
                throw new RuntimeException(
                    "Unable to create component cache directory."
                );
            }
        }

        if (!is_writable($this->cachePath)) {
            throw new RuntimeException(
                "Component cache directory is not writable."
            );
        }
    }

    public function setPranchi(
        \App\Core\Pranchi $pranchi
    ): void {
        $this->pranchi = $pranchi;
    }

    public function render(
        string $viewPath,
        array $props = [],
        string $slot = ''
    ): string {

        $realView = realpath($viewPath);

        if (
            $realView === false ||
            !is_file($realView)
        ) {
            throw new RuntimeException(
                "Component view not found."
            );
        }

        $source = file_get_contents($realView);

        if ($source === false) {
            throw new RuntimeException(
                "Unable to read component view."
            );
        }

        /*
         * Component cache.
         */
        $cacheFile =
            $this->cachePath .
            hash('sha256', $realView) .
            '.php';

        if (
            !file_exists($cacheFile) ||
            filemtime($cacheFile) < filemtime($realView)
        ) {

            if ($this->pranchi === null) {
                throw new RuntimeException(
                    "PRANCHI compiler is not configured."
                );
            }

            /*
             * Component template goes through
             * the normal PRANCHI compiler.
             */
            $compiled =
                $this->pranchi
                    ->compileComponent($source);

            $compiled =
                "<?php\n" .
                "/* PRANCHI component cache */\n" .
                "/* DO NOT EDIT THIS FILE */\n" .
                "?>\n" .
                $compiled;

            $temporary =
                $cacheFile .
                '.' .
                bin2hex(random_bytes(6)) .
                '.tmp';

            if (
                file_put_contents(
                    $temporary,
                    $compiled
                ) === false
            ) {

                @unlink($temporary);

                throw new RuntimeException(
                    "Unable to write component cache."
                );
            }

            if (!rename(
                $temporary,
                $cacheFile
            )) {

                @unlink($temporary);

                throw new RuntimeException(
                    "Unable to finalize component cache."
                );
            }
        }

        /*
         * Variables available to component.
         */
        $__props = $props;
        $__slot  = $slot;

        ob_start();

        try {

            include $cacheFile;

        } catch (Throwable $e) {

            ob_end_clean();

            throw $e;
        }

        return ob_get_clean();
    }
}